In [284]:
import pandas as pd

In [285]:
df=pd.read_csv('public_transport_delays.csv')

In [286]:
df

,trip_id,date,time,transport_type,route_id,origin_station,destination_station,scheduled_departure,scheduled_arrival,actual_departure_delay_min,...,wind_speed_kmh,precipitation_mm,event_type,event_attendance_est,traffic_congestion_index,holiday,peak_hour,weekday,season,delayed
0,T00000,2023-01-01,05:00:00,Tram,Route_15,Station_31,Station_6,05:02:00,05:55:00,12,...,46,13.0,NaN,500,81,0,1,6,Winter,0
1,T00001,2023-01-01,05:15:00,Metro,Route_12,Station_49,Station_32,05:16:00,05:55:00,15,...,11,11.4,NaN,0,53,0,0,6,Autumn,1
2,T00002,2023-01-01,05:30:00,Bus,Route_16,Station_29,Station_42,05:33:00,06:17:00,0,...,31,14.1,Sports,0,67,1,0,6,Autumn,0
3,T00003,2023-01-01,05:45:00,Tram,Route_19,Station_26,Station_18,05:49:00,06:08:00,15,...,41,6.4,NaN,500,84,0,0,6,Winter,1
4,T00004,2023-01-01,06:00:00,Tram,Route_8,Station_18,Station_15,06:00:00,06:35:00,-1,...,30,18.5,NaN,500,46,0,0,6,Spring,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,T01995,2023-01-21,23:45:00,Bus,Route_11,Station_46,Station_39,23:46:00,00:11:00,15,...,35,4.6,NaN,0,96,0,0,5,Winter,1
1996,T01996,2023-01-22,00:00:00,Train,Route_9,Station_44,Station_42,00:03:00,00:41:00,11,...,44,15.4,Festival,0,12,0,1,6,Winter,1
1997,T01997,2023-01-22,00:15:00,Bus,Route_12,Station_4,Station_45,00:18:00,00:35:00,1,...,32,2.7,NaN,0,24,1,0,6,Summer,1
1998,T01998,2023-01-22,00:30:00,Tram,Route_17,Station_29,Station_48,00:34:00,01:18:00,7,...,35,8.8,NaN,2000,23,0,0,6,Summer,1
1999,T01999,2023-01-22,00:45:00,Bus,Route_15,Station_23,Station_14,00:46:00,01:35:00,0,...,1,14.0,NaN,50000,28,0,0,6,Spring,1

In [287]:
df['transport_type']=df['transport_type'].str.lower()

In [288]:
df['origin_station']=df['origin_station'].str.lower()
df['origin_station']=df['origin_station'].str.replace('_',' ')

In [289]:
df['destination_station']=df['destination_station'].str.lower()
df['destination_station']=df['destination_station'].str.replace('_',' ')

In [290]:
df['scheduled_departure']=df['scheduled_departure'].str.slice(0,5)

In [291]:
df['scheduled_arrival']=df['scheduled_arrival'].str.slice(0,5)

In [292]:
df['event_type']=df['event_type'].fillna('no event')

In [293]:
df['holiday']=df['holiday'].map({0:'no',1:'yes','0':'no','1':'yes'})

In [294]:
df['peak_hour']=df['peak_hour'].map({0:'no',1:'yes','0':'no','1':'yes'})

In [295]:
df['season']=df['season'].str.lower()

In [296]:
df['delayed']=df['delayed'].map({0:'no',1:"yes",'0':'no','1':'yes'})

In [297]:
df['weather_condition'] = df['weather_condition'].astype(str).str.lower()

In [298]:
df['weather_condition'].dtype

dtype('O')

In [299]:
df1=df.drop(['trip_id','date','time','route_id','actual_departure_delay_min','actual_departure_delay_min','actual_arrival_delay_min','humidity_percent','wind_speed_kmh','precipitation_mm','weekday'],axis=1)

In [300]:
df1.head()

,transport_type,origin_station,destination_station,scheduled_departure,scheduled_arrival,weather_condition,temperature_C,event_type,event_attendance_est,traffic_congestion_index,holiday,peak_hour,season,delayed
0,tram,station 31,station 6,05:02,05:55,storm,5.1,no event,500,81,no,yes,winter,no
1,metro,station 49,station 32,05:16,05:55,rain,34.0,no event,0,53,no,no,autumn,yes
2,bus,station 29,station 42,05:33,06:17,clear,29.5,Sports,0,67,yes,no,autumn,no
3,tram,station 26,station 18,05:49,06:08,clear,27.4,no event,500,84,no,no,winter,yes
4,tram,station 18,station 15,06:00,06:35,snow,0.1,no event,500,46,no,no,spring,yes

In [301]:
print(df1.isnull().sum())

transport_type              0
origin_station              0
destination_station         0
scheduled_departure         0
scheduled_arrival           0
weather_condition           0
temperature_C               0
event_type                  0
event_attendance_est        0
traffic_congestion_index    0
holiday                     0
peak_hour                   0
season                      0
delayed                     0
dtype: int64

In [302]:
x=df1.drop(['delayed'],axis=1)
y=df1['delayed']

In [303]:
num = []
cat = []

for col in df1:
    if df1[col].dtype == 'object':
        cat.append(col)    # Fixed: Changed [] to ()
    elif df1[col].dtype == 'int64' or df1[col].dtype=='float64':
        num.append(col)    # This one was already correct!

In [304]:
num

['temperature_C', 'event_attendance_est', 'traffic_congestion_index']

In [305]:
cat.remove('delayed')

In [306]:
cat

['transport_type',
 'origin_station',
 'destination_station',
 'scheduled_departure',
 'scheduled_arrival',
 'weather_condition',
 'event_type',
 'holiday',
 'peak_hour',
 'season']

In [307]:
from sklearn.model_selection import train_test_split

In [308]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.25,random_state=42)

In [309]:
x_train

,transport_type,origin_station,destination_station,scheduled_departure,scheduled_arrival,weather_condition,temperature_C,event_type,event_attendance_est,traffic_congestion_index,holiday,peak_hour,season
1738,tram,station 24,station 11,07:33,07:59,cloudy,6.9,Parade,0,53,no,no,autumn
548,train,station 17,station 47,22:04,22:23,clear,3.9,Parade,0,48,no,no,summer
936,train,station 45,station 49,23:01,23:35,cloudy,1.6,no event,0,13,no,no,autumn
1389,bus,station 47,station 46,16:18,16:41,snow,30.3,no event,0,94,no,yes,winter
1607,bus,station 28,station 33,22:49,23:37,storm,-0.0,no event,0,74,no,no,spring
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1130,train,station 7,station 24,23:31,23:58,snow,11.4,Concert,0,38,no,yes,summer
1294,metro,station 24,station 1,16:34,16:56,cloudy,18.9,no event,0,94,no,no,summer
860,metro,station 2,station 18,04:02,04:45,snow,23.1,no event,50000,54,no,no,summer
1459,tram,station 38,station 27,09:46,10:07,cloudy,17.6,no event,2000,69,no,yes,summer
1126,metro,station 37,station 34,22:32,22:54,snow,17.6,no event,0,57,no,no,spring

In [310]:
y_train

1738    yes
548     yes
936      no
1389    yes
1607    yes
       ...
1130     no
1294    yes
860     yes
1459    yes
1126    yes
Name: delayed, Length: 1500, dtype: object

In [311]:
from sklearn.preprocessing import StandardScaler,LabelEncoder,OrdinalEncoder,OneHotEncoder
from sklearn.compose import ColumnTransformer

In [312]:
preprocessing=ColumnTransformer([
    ('num',StandardScaler(),num),
    ('char',OneHotEncoder(handle_unknown='ignore',sparse_output=False),cat)
])

In [313]:
preprocessing

ColumnTransformer(transformers=[('num', StandardScaler(),
                                 ['temperature_C', 'event_attendance_est',
                                  'traffic_congestion_index']),
                                ('char',
                                 OneHotEncoder(handle_unknown='ignore',
                                               sparse_output=False),
                                 ['transport_type', 'origin_station',
                                  'destination_station', 'scheduled_departure',
                                  'scheduled_arrival', 'weather_condition',
                                  'event_type', 'holiday', 'peak_hour',
                                  'season'])])

In [314]:
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier

In [315]:
pipeline=Pipeline([
    ('preprocessor',preprocessing),
    ('model',RandomForestClassifier(n_estimators=100,
    max_depth=10,
    random_state=42,
    class_weight='balanced'))
]).fit(x_train,y_train)

In [316]:
y_pred=pipeline.predict(x_test)

In [317]:
y_pred

array(['yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'no', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'no', 'yes', 'yes',
       'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'yes', 'no', 'yes',
       'yes', 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'no', 'no',
       'yes', 'yes', 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'no', 'yes', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'no', 'yes', 'no', 'yes', 'yes', 'yes',
       'yes', 'no', 'yes', 'yes', 'yes', 'yes', 'no', 'yes', 'no', 'yes',
       'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'no', 'yes', 'yes',
       'yes', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'no', 'yes',
       'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'no', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'yes', 'no', 'no', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'no',
       'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'no', 'no', 'yes', 'no', 'yes', 'yes',
       'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'yes', 'no', 'yes', 'yes',
       'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'no', 'yes', 'yes', 'no', 'yes', 'yes', 'yes', 'no', 'yes',
       'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'no', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'no', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'no',
       'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'no', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes',
       'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'no',
       'yes', 'yes'], dtype=object)

In [318]:
y_train.value_counts()

delayed
yes    1127
no      373
Name: count, dtype: int64

In [319]:
y_test

1860     no
353     yes
1333    yes
905      no
1289    yes
       ...
765     yes
1356    yes
408      no
1614     no
694     yes
Name: delayed, Length: 500, dtype: object

In [320]:
from sklearn.metrics import f1_score

In [321]:
f1=f1_score(y_test, y_pred, pos_label='yes')
print(f1)

0.8238153098420413